triggerHavenBag = true
OPEN_BAGS = true
banque = false

module = {}

path1 = {
    {map = "2883593", path = "havenbag"},
	{map = "0,0", path = "zaap(191105026)"},
	{map = "5,-18", path = "bottom"},
	{map = "5,-17", path = "bottom", gather = true},
	{map = "5,-16", path = "bottom", gather = true},
	{map = "5,-15", path = "left", gather = true},
	{map = "4,-15", path = "left", gather = true},
	{map = "3,-15", path = "bottom", gather = true},
	{map = "8,-14", path = "right"},
	{map = "3,-14", path = "right", gather = true},
	{map = "4,-14", path = "right", gather = true},
	{map = "5,-14", path = "right", gather = true},
	{map = "6,-14", path = "right", gather = true},
	{map = "7,-14", path = "right", gather = true},
	{map = "9,-14", path = "right", gather = true},
	{map = "10,-14", path = "bottom", gather = true},
	{map = "10,-13", path = "left", gather = true},
	{map = "9,-13", path = "left", gather = true},
	{map = "8,-13", path = "left", gather = true},
	{map = "7,-13", path = "left", gather = true},
	{map = "6,-13", path = "left", gather = true},
	{map = "5,-13", path = "left", gather = true},
	{map = "4,-13", path = "left", gather = true},
	{map = "3,-13", path = "bottom", gather = true},
	{map = "3,-12", path = "right", gather = true},
	{map = "4,-12", path = "right", gather = true},
	{map = "5,-12", path = "right", gather = true},
	{map = "6,-12", path = "right", gather = true},
	{map = "7,-12", path = "right", gather = true},
	{map = "8,-12", path = "right", gather = true},
	{map = "9,-12", path = "right", gather = true},
	{map = "10,-12", path = "right", gather = true},
	{map = "11,-12", path = "bottom", gather = true},
	{map = "11,-11", path = "left", gather = true},
	{map = "9,-11", path = "left", gather = true},
	{map = "8,-11", path = "left", gather = true},
	{map = "7,-11", path = "left", gather = true},
	{map = "6,-11", path = "left", gather = true},
	{map = "5,-11", path = "left", gather = true},
	{map = "3,-11", path = "bottom", gather = true},
	{map = "3,-10", path = "right", gather = true},
	{map = "4,-10", path = "right", gather = true},
	{map = "5,-10", path = "right", gather = true},
	{map = "6,-10", path = "right", gather = true},
	{map = "7,-10", path = "right", gather = true},
	{map = "8,-10", path = "bottom", gather = true},
	{map = "8,-9", path = "left", gather = true},
	{map = "6,-9", path = "left", gather = true},
	{map = "5,-9", path = "left", gather = true},
	{map = "3,-9", path = "left", gather = true},
	{map = "7,-9", path = "left"},
	{map = "4,-9", path = "left"},
	{map = "10,-11", path = "left"},
	{map = "4,-11", path = "left"},
	{map = "2,-9", path = "top"},
	{map = "2,-11", path = "top"},
	{map = "2,-12", path = "top"},
	{map = "2,-13", path = "top"},
	{map = "2,-14", path = "top"},
	{map = "2,-15", path = "top", gather = true},
	{map = "4,-16", path = "right"},
	{map = "4,-18", path = "right"},
	{map = "2,-16", path = "right", gather = true},
	{map = "3,-16", path = "right", gather = true},
	{map = "2,-10", path = "left"},
	{map = "1,-10", path = "top"},
	{map = "1,-11", path = "right"},
}

path2 = {
    {map = "2883593", path = "havenbag"},
	{map = "0,0", path = "zaap(191105026)"},
	{map = "192415750", path = "424"},
	{map = "2,-9", path = "top"},
	{map = "2,-10", path = "top"},
	{map = "2,-11", path = "top"},
	{map = "2,-12", path = "top"},
	{map = "2,-13", path = "top"},
	{map = "2,-14", path = "top"},
	{map = "3,-9", path = "top"},
	{map = "4,-9", path = "top"},
	{map = "5,-9", path = "top"},
	{map = "6,-9", path = "top"},
	{map = "7,-9", path = "top"},
	{map = "8,-9", path = "top"},
	{map = "9,-10", path = "top"},
	{map = "8,-10", path = "top"},
	{map = "7,-10", path = "top"},
	{map = "6,-10", path = "top"},
	{map = "5,-10", path = "top"},
	{map = "4,-10", path = "top"},
	{map = "3,-10", path = "top"},
	{map = "3,-11", path = "top"},
	{map = "4,-11", path = "top"},
	{map = "5,-11", path = "top"},
	{map = "6,-11", path = "top"},
	{map = "7,-11", path = "top"},
	{map = "8,-11", path = "top"},
	{map = "9,-11", path = "top"},
	{map = "10,-11", path = "top"},
	{map = "11,-11", path = "top"},
	{map = "10,-12", path = "top"},
	{map = "9,-12", path = "top"},
	{map = "8,-12", path = "top"},
	{map = "7,-12", path = "top"},
	{map = "6,-12", path = "top"},
	{map = "5,-12", path = "top"},
	{map = "4,-12", path = "top"},
	{map = "3,-12", path = "top"},
	{map = "3,-13", path = "top"},
	{map = "4,-13", path = "top"},
	{map = "5,-13", path = "top"},
	{map = "6,-13", path = "top"},
	{map = "7,-13", path = "top"},
	{map = "8,-13", path = "top"},
	{map = "9,-13", path = "top"},
	{map = "10,-13", path = "top"},
	{map = "11,-12", path = "left"},
	{map = "10,-14", path = "left"},
	{map = "9,-14", path = "left"},
	{map = "8,-14", path = "left"},
	{map = "7,-14", path = "left"},
	{map = "6,-14", path = "left"},
	{map = "5,-14", path = "top"},
	{map = "5,-15", path = "top"},
	{map = "5,-16", path = "top"},
	{map = "5,-17", path = "top"},
	{map = "4,-14", path = "top"},
	{map = "3,-14", path = "top"},
	{map = "2,-16", path = "right"},
	{map = "2,-15", path = "right"},
	{map = "3,-15", path = "right"},
	{map = "3,-16", path = "right"},
	{map = "4,-16", path = "right"},
	{map = "4,-15", path = "right"},
	{map = "5,-18", path = "left"},
	{map = "4,-18", path = "left"},
	{map = "3,-18", path = "left"},
	{map = "2,-18", path = "left"},
	{map = "1,-18", path = "left"},
	{map = "0,-18", path = "bottom", gather = true},
	{map = "0,-17", path = "bottom", gather = true},
	{map = "0,-16", path = "bottom", gather = true},
	{map = "0,-15", path = "left", gather = true},
	{map = "-1,-15", path = "left", gather = true},
	{map = "-2,-15", path = "left", gather = true},
	{map = "-4,-15", path = "top", gather = true},
	{map = "-3,-15", path = "left"},
	{map = "-4,-16", path = "right"},
	{map = "-3,-16", path = "right", gather = true},
	{map = "-2,-16", path = "right", gather = true},
	{map = "-1,-16", path = "top", gather = true},
	{map = "-1,-17", path = "left", gather = true},
	{map = "-2,-17", path = "left"},
	{map = "-3,-17", path = "left", gather = true},
	{map = "-4,-17", path = "left"},
	{map = "-5,-17", path = "top"},
	{map = "-5,-18", path = "right", gather = true},
	{map = "-4,-18", path = "right", gather = true},
	{map = "-3,-18", path = "right", gather = true},
	{map = "-2,-18", path = "right", gather = true},
	{map = "-1,-18", path = "top", gather = true},
	{map = "-1,-19", path = "left", gather = true},
	{map = "-2,-19", path = "left", gather = true},
	{map = "-3,-19", path = "top", gather = true},
	{map = "-3,-20", path = "right", gather = true},
	{map = "-1,-20", path = "right", gather = true},
	{map = "0,-20", path = "top", gather = true},
	{map = "-2,-20", path = "right"},
	{map = "0,-21", path = "left", gather = true},
	{map = "-1,-21", path = "left", gather = true},
	{map = "-2,-21", path = "left", gather = true},
	{map = "-3,-21", path = "top", gather = true},
	{map = "-3,-22", path = "right", gather = true},
	{map = "-2,-22", path = "right"},
	{map = "-1,-22", path = "right"},
	{map = "0,-22", path = "right", gather = true},
	{map = "2,-22", path = "top"},
	{map = "2,-23", path = "top", gather = true},
	{map = "2,-24", path = "top"},
	{map = "2,-25", path = "left", gather = true},
	{map = "0,-25", path = "bottom", gather = true},
	{map = "0,-24", path = "bottom", gather = true},
	{map = "0,-23", path = "left", gather = true},
	{map = "-1,-23", path = "left", gather = true},
	{map = "1,-25", path = "left"},
	{map = "1,-22", path = "right"},
	{map = "-2,-23", path = "left"},
	{map = "-3,-23", path = "left"},
	{map = "-4,-23", path = "bottom"},
	{map = "-4,-22", path = "bottom"},
	{map = "-4,-21", path = "bottom"},
	{map = "-4,-20", path = "bottom"},
	{map = "-4,-19", path = "left"},
	{map = "-5,-19", path = "left"},
	{map = "-6,-19", path = "bottom"},
	{map = "-6,-17", path = "bottom"},
	{map = "-6,-18", path = "bottom"},
	{map = "-6,-16", path = "right"},
	{map = "-5,-16", path = "bottom"},
	{map = "-5,-15", path = "bottom"},
	{map = "-5,-14", path = "right", gather = true},
	{map = "-4,-14", path = "right"},
	{map = "-2,-14", path = "right"},
	{map = "-3,-14", path = "right"},
	{map = "-1,-14", path = "right"},
	{map = "0,-14", path = "right"},
	{map = "1,-14", path = "top"},
	{map = "1,-15", path = "top"},
	{map = "1,-16", path = "top"},
	{map = "1,-17", path = "top"},
}

path3 = {
    {map = "2883593", path = "havenbag" },
	{map = "0,0", path = "zaap(73400320)"},
	{map = "5,-18", path = "zaap(73400320)"},
	{map = "84935175", path = "425"},
	{map = "-16,4", path = "left"},
	{map = "-17,4", path = "left"},
	{map = "5,-18", path = "left"},
	{map = "4,-18", path = "left"},
	{map = "3,-18", path = "left"},
	{map = "2,-18", path = "left"},
	{map = "1,-18", path = "left"},
	{map = "-2,-20", path = "bottom"},
	{map = "2,-25", path = "left"},
	{map = "1,-25", path = "left"},
	{map = "2,-23", path = "left"},
	{map = "1,-23", path = "left"},
	{map = "0,-25", path = "bottom"},
	{map = "0,-23", path = "bottom"},
	{map = "0,-24", path = "bottom"},
	{map = "0,-22", path = "bottom"},
	{map = "-1,-23", path = "bottom"},
	{map = "-1,-22", path = "bottom"},
	{map = "0,-21", path = "bottom"},
	{map = "-1,-21", path = "bottom"},
	{map = "-1,-20", path = "bottom"},
	{map = "0,-20", path = "bottom"},
	{map = "0,-19", path = "bottom"},
	{map = "-1,-19", path = "bottom"},
	{map = "-3,-20", path = "bottom"},
	{map = "-3,-21", path = "bottom"},
	{map = "-2,-21", path = "bottom"},
	{map = "-3,-22", path = "bottom"},
	{map = "-3,-19", path = "bottom"},
	{map = "-2,-19", path = "bottom"},
	{map = "0,-18", path = "left"},
	{map = "-1,-18", path = "left"},
	{map = "-2,-18", path = "left"},
	{map = "-3,-18", path = "left"},
	{map = "-4,-18", path = "left"},
	{map = "0,-17", path = "left"},
	{map = "-1,-17", path = "left"},
	{map = "-2,-17", path = "left"},
	{map = "-3,-17", path = "left"},
	{map = "-4,-17", path = "left"},
	{map = "-5,-17", path = "left"},
	{map = "-5,-18", path = "left"},
	{map = "0,-16", path = "left"},
	{map = "-1,-16", path = "left"},
	{map = "-2,-16", path = "left"},
	{map = "-3,-16", path = "left"},
	{map = "-4,-16", path = "left"},
	{map = "0,-15", path = "left"},
	{map = "-1,-15", path = "left"},
	{map = "-2,-15", path = "left"},
	{map = "-3,-15", path = "left"},
	{map = "-4,-15", path = "left"},
	{map = "-5,-14", path = "top"},
	{map = "-5,-15", path = "top"},
	{map = "-5,-16", path = "top"},
	{map = "-6,-18", path = "left"},
	{map = "-6,-17", path = "left"},
	{map = "-7,-18", path = "bottom"},
	{map = "-7,-17", path = "bottom"},
	{map = "-7,-16", path = "bottom"},
	{map = "-7,-15", path = "bottom"},
	{map = "-7,-14", path = "bottom"},
	{map = "-7,-13", path = "bottom"},
	{map = "-7,-11", path = "bottom"},
	{map = "-7,-12", path = "bottom"},
	{map = "-7,-10", path = "bottom"},
	{map = "-7,-9", path = "bottom"},
	{map = "-7,-8", path = "bottom"},
	{map = "-7,-7", path = "left"},
	{map = "-8,-7", path = "left"},
	{map = "-9,-7", path = "left"},
	{map = "-10,-7", path = "left"},
	{map = "-11,-7", path = "left"},
	{map = "-12,-7", path = "left"},
	{map = "-13,-7", path = "bottom"},
	{map = "-13,-6", path = "left"},
	{map = "-14,-6", path = "left"},
	{map = "-15,-6", path = "left"},
	{map = "-16,-6", path = "bottom"},
	{map = "-16,-5", path = "bottom"},
	{map = "-16,-4", path = "bottom"},
	{map = "-16,-3", path = "bottom"},
	{map = "-16,-2", path = "bottom"},
	{map = "-16,-1", path = "bottom"},
	{map = "-16,0", path = "bottom"},
	{map = "-16,1", path = "left"},
	{map = "-17,1", path = "left"},
	{map = "-18,1", path = "bottom"},
	{map = "-18,2", path = "bottom"},
	{map = "-18,3", path = "bottom"},
	{map = "-18,4", path = "left", gather = true},
	{map = "-19,4", path = "left", gather = true},
	{map = "-20,4", path = "left", gather = true},
	{map = "-21,4", path = "left", gather = true},
	{map = "-22,4", path = "top", gather = true},
	{map = "-22,3", path = "right", gather = true},
	{map = "-21,3", path = "right", gather = true},
	{map = "-20,3", path = "right", gather = true},
	{map = "-19,3", path = "top", gather = true},
	{map = "-19,2", path = "left", gather = true},
	{map = "-20,2", path = "left", gather = true},
	{map = "-21,2", path = "left", gather = true},
	{map = "-22,2", path = "left", gather = true},
	{map = "-23,2", path = "top", gather = true},
	{map = "-23,1", path = "right", gather = true},
	{map = "-22,1", path = "top", gather = true},
	{map = "-20,1", path = "top", gather = true},
	{map = "-21,0", path = "bottom", gather = true},
	{map = "-19,0", path = "bottom", gather = true},
	{map = "-19,1", path = "right", gather = true},
	{map = "-22,0", path = "right", gather = true},
	{map = "-21,1", path = "right", gather = true},
	{map = "-20,0", path = "top", gather = true},
	{map = "-20,-1", path = "right"},
	{map = "-19,-1", path = "bottom"},
}

path4 = {
	{map = "2883593", path = "havenbag"},
	{map = "0,0", path = "zaap(154642)"},
	{map = "86511105", path = "452"},
	{map = "5,-18", path = "zaap(154642)"},
	{map = "26,-37", path = "zaap(154642)"},
	{map = "-23,1", path = "right"},
	{map = "-23,2", path = "right"},
	{map = "-22,2", path = "right"},
	{map = "-22,1", path = "right"},
	{map = "-22,0", path = "right"},
	{map = "-22,3", path = "right"},
	{map = "-22,4", path = "right"},
	{map = "-21,4", path = "right"},
	{map = "-21,3", path = "right"},
	{map = "-21,2", path = "right"},
	{map = "-21,1", path = "right"},
	{map = "-21,0", path = "right"},
	{map = "-20,1", path = "right"},
	{map = "-19,1", path = "right"},
	{map = "-18,1", path = "right"},
	{map = "-17,1", path = "right"},
	{map = "-20,4", path = "top"},
	{map = "-20,3", path = "top"},
	{map = "-20,2", path = "top"},
	{map = "-19,4", path = "top"},
	{map = "-19,3", path = "top"},
	{map = "-19,2", path = "top"},
	{map = "-19,0", path = "bottom"},
	{map = "-20,0", path = "bottom"},
	{map = "27,-37", path = "left", gather = true},
	{map = "28,-37", path = "left", gather = true},
	{map = "28,-39", path = "bottom", gather = true},
	{map = "28,-40", path = "bottom", gather = true},
	{map = "28,-41", path = "bottom", gather = true},
	{map = "28,-38", path = "bottom"},
	{map = "28,-42", path = "bottom"},
	{map = "28,-43", path = "bottom", gather = true},
	{map = "22,-42", path = "bottom"},
	{map = "20,-37", path = "bottom"},
	{map = "20,-35", path = "bottom"},
	{map = "20,-34", path = "bottom"},
	{map = "20,-33", path = "right"},
	{map = "23,-31", path = "bottom"},
	{map = "26,-30", path = "top"},
	{map = "28,-31", path = "right"},
	{map = "28,-34", path = "top"},
	{map = "24,-36", path = "right"},
	{map = "25,-36", path = "right"},
	{map = "26,-36", path = "top"},
	{map = "20,-36", path = "bottom"},
	{map = "20,-39", path = "bottom"},
	{map = "20,-38", path = "bottom"},
	{map = "21,-40", path = "bottom"},
	{map = "22,-41", path = "bottom"},
	{map = "27,-43", path = "right"},
	{map = "28,-35", path = "top"},
	{map = "28,-36", path = "top"},
	{map = "28,-33", path = "top"},
	{map = "26,-31", path = "top"},
	{map = "26,-32", path = "top"},
	{map = "29,-31", path = "top"},
	{map = "29,-32", path = "top"},
	{map = "29,-33", path = "left"},
	{map = "27,-31", path = "right"},
	{map = "27,-32", path = "bottom"},
	{map = "26,-33", path = "right"},
	{map = "27,-33", path = "right"},
	{map = "21,-31", path = "right"},
	{map = "22,-31", path = "right"},
	{map = "23,-30", path = "right"},
	{map = "24,-30", path = "right"},
	{map = "25,-30", path = "right"},
	{map = "23,-42", path = "left"},
	{map = "24,-42", path = "left"},
	{map = "25,-42", path = "left"},
	{map = "26,-42", path = "left"},
	{map = "27,-42", path = "left"},
	{map = "21,-39", path = "left"},
	{map = "22,-40", path = "left"},
	{map = "21,-33", path = "bottom"},
	{map = "21,-32", path = "bottom"},
	{map = "-51,12", path = "left", gather = true},
	{map = "-52,11", path = "left", gather = true},
	{map = "-54,11", path = "top", gather = true},
	{map = "-55,10", path = "bottom", gather = true},
	{map = "-55,13", path = "left", gather = true},
	{map = "-56,13", path = "bottom", gather = true},
	{map = "-56,15", path = "right", gather = true},
	{map = "-55,15", path = "right", gather = true},
	{map = "-54,15", path = "right", gather = true},
	{map = "-53,15", path = "top", gather = true},
	{map = "-51,13", path = "bottom", gather = true},
	{map = "-51,14", path = "right", gather = true},
	{map = "-50,14", path = "bottom", gather = true},
	{map = "-50,15", path = "left", gather = true},
	{map = "-51,15", path = "left", gather = true},
	{map = "-52,15", path = "bottom", gather = true},
	{map = "-52,16", path = "right", gather = true},
	{map = "-51,16", path = "bottom", gather = true},
	{map = "-51,17", path = "right", gather = true},
	{map = "-50,18", path = "left", gather = true},
	{map = "-51,18", path = "bottom", gather = true},
	{map = "-51,19", path = "left", gather = true},
	{map = "-52,19", path = "bottom", gather = true},
	{map = "-52,20", path = "left", gather = true},
	{map = "-53,20", path = "left", gather = true},
	{map = "-54,20", path = "bottom", gather = true},
	{map = "-54,21", path = "left", gather = true},
	{map = "-55,21", path = "top", gather = true},
	{map = "-52,12", path = "top"},
	{map = "-54,10", path = "left(336)"},
	{map = "-55,11", path = "bottom"},
	{map = "-55,12", path = "bottom"},
	{map = "-56,14", path = "bottom"},
	{map = "-53,14", path = "top"},
	{map = "-53,13", path = "right", gather = true},
	{map = "-52,13", path = "right"},
	{map = "-53,11", path = "left"},
	{map = "-54,12", path = "top"},
	{map = "-53,12", path = "left", gather = true},
	{map = "-50,17", path = "bottom"},
	{map = "-55,20", path = "top"},
	{map = "-55,19", path = "right"},
	{map = "-54,18", path = "top"},
	{map = "-54,17", path = "left"},
	{map = "-56,16", path = "bottom"},
	{map = "-56,20", path = "bottom"},
	{map = "-56,17", path = "bottom", gather = true},
	{map = "-56,18", path = "bottom", gather = true},
	{map = "-56,19", path = "bottom", gather = true},
	{map = "-55,17", path = "top", gather = true},
	{map = "-54,19", path = "top", gather = true},
	{map = "-55,16", path = "left", gather = true},
	{map = "-56,21", path = "bottom", gather = true},
	{map = "-56,22", path = "right", gather = true},
	{map = "-54,22", path = "right", gather = true},
	{map = "-53,22", path = "right", gather = true},
	{map = "-55,22", path = "right"},
	{map = "-52,22", path = "top"},
	{map = "-52,21", path = "right", gather = true},
	{map = "-51,21", path = "right"},
	{map = "-50,21", path = "right"},
	{map = "-49,21", path = "top"},
	{map = "-49,20", path = "top"},
	{map = "-49,19", path = "top"},
	{map = "-49,18", path = "top"},
	{map = "-49,17", path = "top"},
	{map = "-49,16", path = "top"},
	{map = "-49,15", path = "top"},
	{map = "-49,14", path = "top"},
	{map = "-49,13", path = "top"},
	{map = "-49,12", path = "left"},
	{map = "-50,12", path = "left"},
	{map = "-48,19", path = "left"},
	{map = "-47,19", path = "left"},
	{map = "-46,19", path = "left"},
	{map = "-47,21", path = "top"},
	{map = "-47,20", path = "top"},
	{map = "-46,18", path = "bottom"},
}

mandragore =
{
  {map = "2883593", path = "havenbag"},
	{map = "0,0", path = "zaap(154642)"},
}

selectedPath = path1

function pathSelection()
    if job:level(26) < 40 then
    	GATHER = {254,255}
        selectedPath = path1
    elseif job:level(26) >= 40 and job:level(26) < 80 then
    	GATHER = {67,66,254,255}
        selectedPath = path2
    elseif job:level(26) >= 80 and job:level(26) < 140 then
    	GATHER = {68,67,66,254,255}
        selectedPath = path3
    elseif job:level(26) >= 140 and job:level(26) < 200 then
    	GATHER = {256,257,68,67,66,254,255}
    	selectedPath = path4
    elseif job:level(26) == 200 and tonumber(os.date("%M")) < 30 then
      GATHER = {256,257,68,67,66,254,255}
      selectedPath = path4
    elseif job:level(26) ==200 and tonumber(os.date("%M")) <= 60 then
      GATHER = {256,257,68,67,66,254,255}
      selectedPath = path1
    end
end


function module:move()
	pathSelection()
	for x,y in pairs(selectedPath) do
		if y.map == map:currentMap() or y.map == tostring(map:currentMapId()) then
			return selectedPath
		end
	end
	return {
		{map = map:currentMap(), path = "havenbag"},
	}
end

return module
